### ISSUE TITLE
Als gemeente wil ik een duidelijk beeld van de positionering Common Ground en de huidige GEMMA. (-2)

### ISSUE THREAD

**Issue by jgortmaker1** [VNG-Realisatie/cg-architectuur#10]
...zodat ik weet hoe deze zich tot elkaar verhouden en ik weet welke kaders ik waarop moet toepassen.

**Definition of ready**

- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en leesbaar)
- [ ] Voorzien van Definition of Done 
- [ ] Voorzien van taken (naam, uren, smart)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Users en stakeholder benoemd
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [ ] Document gereed en afgestemd op doelgroep
- [ ] Potentieel publiceerbaar/beschikbaar voor users en stakeholders
- [ ] Peer review heeft plaatsgevonden
- [ ] Demo-gereed (kan getoond worden tijdens demo en is demo materiaal is gereed)
- [ ] ...

**Users**

- ...

**Stakeholders**

- ...

**Acceptatiecriteria**

- duidelijk en leesbaar voor doelgroep (users/stakeholders
- ...

**Globale oplossingrichting**

...

**Taken**

- [ ] ...
- [ ] ...
- [ ] ...
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by hdksi** [comment]
Zie ook #82

**Comment by TCIMEddy** [comment]
Dubbel met #82
