### ISSUE TITLE
"Ongeduld" bij Taskforce

### ISSUE THREAD

**Issue by jgortmaker1** [VNG-Realisatie/cg-architectuur#123]
TSA wil sneller resultaten (m.n. principes) dan volgens de sprint-planning lukt...
hier moeten we op een goede manier mee omgaan.

**Comment by TCIMEddy** [comment]
Morgen maar even kijken of we dit kunnen oppakken en beïnvloeden

**Comment by TCIMEddy** [comment]
@jgortmaker1 ongeduld blijft maar is dit nog een impediment? Zo niet graag close en comment

**Comment by jgortmaker1** [comment]
dit zal doorlopend het geval blijven zijn. Kunnen we ook niet meer aan doen dan we al doen. mag voor mij dus op close.
