### ISSUE TITLE
Als ontwikkelaar wil ik weten aan welke acceptatiecriteria een door VNG landelijk ontwikkelde/beschikbaar gesteld product moet voldoen zodat het goed beheerd kan worden. (2)

### ISSUE THREAD

**Issue by MHulst** [VNG-Realisatie/cg-architectuur#41]
**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en leesbaar)
- [x] Voorzien van Definition of Done 
- [x] Voorzien van taken (naam, uren, smart)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Users en stakeholder benoemd
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [x] Document gereed en afgestemd op doelgroep
- [x] Lijst met algemene acceptatiecriteria
- [x] Peer review heeft plaatsgevonden
- [x] Demo-gereed (kan getoond worden tijdens demo en is demo materiaal is gereed)
- [x] Product Owner akkoord

**Users**

- product owners
- ontwikkelaars
- beheerders

**Stakeholders**

- beheer
- product owners

**Acceptatiecriteria**

- [x] duidelijk en leesbaar voor doelgroep (users/stakeholders)
- [x] document met acceptatiecriteria

**Globale oplossingrichting**

Om te kunnen beheren, zijn er criteria waar de producten aan moeten voldoen. Deze acceptatie criteria lopen uiteen van architectuur, ontwerpdocumenten, als code, installatiehandleidingen etc. 

**Taken**

- [x] Algemene acceptatiecriteria opstellen
- [x] Acceptatiecriteria voor infrastructuur opstellen
- [x] Acceptatiecriteria voor applicaties opstellen
- [x] Peer review
- [ ] Materiaal voor Demo
- [ ] ...

**Comment by MHulst** [comment]
Document met Acceptatie criteria

**Comment by TCIMEddy** [comment]
@MHulst @jgortmaker1 Wat mij prima springbaar dus in to do gezet in sprint 1.

**Comment by TCIMEddy** [comment]
@MHulst hulp nodig laat het me weten (niet inhoudelijk uiteraard :-)

**Comment by TCIMEddy** [comment]
@MHulst separaat lekenreview gegeven.

**Comment by TCIMEddy** [comment]
@MHulst wil je bij de assignees aangeven wie 'verplicht' moeten reviewen

**Comment by jgortmaker1** [comment]
mooi setje eisen. niets toe te voegen aan andere reviews en vragen

**Comment by TCIMEddy** [comment]
Feedback tijdens demo:

**Comment by TCIMEddy** [comment]
Wat mij betreft publiceerbaar en done (en close deze dus)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als gemeentelijk architect wil ik graag een Archimate repository met CG-elementen om daar gebruik van te maken bij gemeentelijk beleid en ontwikkeling (1)](https://trello.com/c/yH52phqD/127-als-gemeentelijk-architect-wil-ik-graag-een-archimate-repository-met-cg-elementen-om-daar-gebruik-van-te-maken-bij-gemeentelijk)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als ontwikkelaar wil ik weten aan welke acceptatiecriteria een door VNG landelijk ontwikkelde/beschikbaar gesteld product moet voldoen zodat het goed beheerd kan worden. (2)](https://trello.com/c/nySjtO9C/126-als-ontwikkelaar-wil-ik-weten-aan-welke-acceptatiecriteria-een-door-vng-landelijk-ontwikkelde-beschikbaar-gesteld-product-moet-v)
