### ISSUE TITLE
Als team wil ik een heldere publicatieplaats voor al onze architectuurproducten

### ISSUE THREAD

**Issue by jgortmaker1** [VNG-Realisatie/cg-architectuur#61]
zodat in één oogopslag duidelijk is welke producten beschikbaar zijn en wat de status daarvan is

Zelfde als #80 

... ik kan bepalen welke impact dat op die bouwstenen heeft.

**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en leesbaar)
- [x] Voorzien van Definition of Done
- [x] Voorzien van taken (naam, uren, smart)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Users en stakeholder benoemd
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [x] Beschikbaar voor users en stakeholders

**Users**

- Squad Architectuur
- Architecten (leveranciers/gemeenten)
- Ontwikkelaars (leveranciers/gemeenten)
- Overige gebruikers gemeenten (processen, applicatiebeheer, informatiemanagement)

**Stakeholders**

- VNG Realisatie
- Gemeenten
- Leveranciers

**Acceptatiecriteria**

- Duidelijk en leesbaar voor doelgroep (users/stakeholders)

**Globale oplossingsrichting**

- Een overzicht van mogelijke publicatieplaatsen/platforms met hun voor- en nadelen i.r.t. de gewenste kenmerken en functionaliteit.

**Taken**

- [x] benoemen/klaarmaken publicatieplaats/platform intern/extern

**Comment by hdksi** [comment]
Vergelijkbaar met #80

**Comment by TCIMEddy** [comment]
@hdksi Als het intern betreft dan is dit gereed neem ik aan (met Microsoft Teams) toch? Als dat het geval is kan deze close en naar review

**Comment by TCIMEddy** [comment]
@hdksi nu beter doorgelezen sorry nog niet gereed?

**Comment by hdksi** [comment]
Wat besluitvorming betreft klaar, daarmee is de US beantwoord:
- intern: MS Teams
- extern: GEMMA Online.
Beide omgevingen kunnen nog wel wat verbetering gebruiken.
