### ISSUE TITLE
Als geïnteresseerde in Common Ground wil ik een heldere, actuele en eenduidige omschrijving van de architectuur van Common Ground (vijflagenmodel + uitleg),  (0)

### ISSUE THREAD

**Issue by jgortmaker1** [VNG-Realisatie/cg-architectuur#7]
...zodat ik de meest recente architectuur altijd kan vinden op een vaste plaats (bij de bron)
**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en leesbaar)
- [ ] Voorzien van Definition of Done 
- [ ] Voorzien van taken (naam, uren, smart)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Users en stakeholder benoemd
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] Document gereed en afgestemd op doelgroep
- [ ] Potentieel publiceerbaar/beschikbaar voor users en stakeholders
- [ ] Peer review heeft plaatsgevonden
- [ ] Demo-gereed (kan getoond worden tijdens demo en is demo materiaal is gereed)
- [ ] ...

**Users**
- 
- 
-

**Stakeholders**
- 
- 

**Acceptatiecriteria**
- [ ] duidelijk en leesbaar voor doelgroep (users/stakeholders
- [ ] ...
- [ ] ...

**Globale oplossingrichting**
- [ ] ...
- [ ] ...

**Taken**
- [ ] ...
- [ ] ...

**Comment by JWEmmen** [comment]
Hoe zit het de ontwikkelingen voor een "sterke digitale identiteit". Jorinde is een belangrijke kartrekker op dit onderdeel.....? Zou graag de samenhang willen zien :)

**Comment by arnoudquanjer** [comment]
@jgortmaker1 kan worden samengevoegd met #8

**Comment by jgortmaker1** [comment]
het doel, de "zodat" is anders..,maar dat valt me ook nu pas op.

ik vermoed ook dat jij dan eigenlijk met deze US aan de slag bent geweest ipv #8 ....

Maar ik zal deze sluiten. over transitie hebben we al andere USs

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#7 ⁃ Als geïnteresseerde in Common Ground wil ik een heldere, actuele en eenduidige omschrijving van de architectuur van Common Ground (vijflagenmodel + uitleg),  (0)](https://trello.com/c/71uPM89y/160-7-als-ge%C3%AFnteresseerde-in-common-ground-wil-ik-een-heldere-actuele-en-eenduidige-omschrijving-van-de-architectuur-van-common-grou)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als beheerder wil ik voorzieningen en richtlijnen om CG API's te kunnen beveiligen zodat de risico's van misbruik van de API's worden beperkt. (3)](https://trello.com/c/lEMQBfYA/104-als-beheerder-wil-ik-voorzieningen-en-richtlijnen-om-cg-apis-te-kunnen-beveiligen-zodat-de-risicos-van-misbruik-van-de-apis-word)
