### ISSUE TITLE
Als architect voor de GEMMA doelarchitectuur Omgevingswet wil ik weten hoe Common Ground zich in de doelarchitectuur gaat vertalen, zodat we een haalbare en op Common Ground gestoelde / voorbereide doelarchitectuur kunnen opleveren.  (5) 

### ISSUE THREAD

**Issue by NCouwenbergh** [VNG-Realisatie/cg-architectuur#72]
**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en leesbaar)
- [x] Voorzien van Definition of Done 
- [x] Voorzien van taken (naam, uren, smart)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Users en stakeholder benoemd
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [x] Document gereed en afgestemd op doelgroep
- [x] Potentieel publiceerbaar/beschikbaar voor users en stakeholders
- [x] Peer review heeft plaatsgevonden
- [ ] Demo-gereed (kan getoond worden tijdens demo en is demo materiaal is gereed)

**Users**

- Architecten Omgevingswet

**Stakeholders**

- VNG realisatie
- VNG Realisatie Architecten
- Gemeenten

**Acceptatiecriteria**

- [x] duidelijk en leesbaar voor doelgroep (users/stakeholders)
- [x] Via GEMMA online ontsloten

**Globale oplossingrichting**

We willen een doelarchitectuur voor de Omgevingswet maken die voldoet aan de eisen van Common Ground. Dit is eigenlijk een concern / een vraag. Voor het beantwoorden van deze vraag zijn producten nodig vanuit Common Ground. Denk hierbij aan visie, principes, groeipad etc. Deze zijn echter nog niet beschikbaar. 

Om toch met de doelarchitectuur  te kunnen starten, baseren we de deze op dat wat nu al bekend is over Common Ground. Op het moment dat in volgende sprints meer Common Ground producten beschikbaar komen, kunnen deze op de doelarchitectuur toegepast worden. Zo werken we iteratief aan de doelarchitectuur.

**Taken**
- [ ] verwerken van 5 lagen model in Omgevingswet views (Nils)
- [ ] verwerken van scheiding van proces en data in architectuur (Nils)
- [ ] updaten van teksten mbt common ground (Nils)

**Comment by WimBakkeren** [comment]
Het is me niet duidelijk wat hier het op te leveren product is. Is dat de de doelarchitectuur voor de Omgevingswet waarin Common Ground (impliciet) is verwerkt? Of is het een product wat duidelijk maakt hoe Common Ground in het algemeen in doelarchitecturen verwerkt moet worden. Dat laatste lijkt me meer een product van de Squad Architectuur. Het eerste is een product van, in dit geval, het project DSO-CG.
Maw, in mijn ogen levert de Squad Architectuur een product dat (domein-)projecten helpt om Common Ground in hun domeinarchitecturen te verwerken.

**Comment by tschijv** [comment]
Laten we beginnen met de doel/referentiearchitectuur OW voor te leggen aan de Squad. Met een oplegger erbij welke CG/Gegevenslandschap-elementen waar in verwerkt zijn. Van daar uit kan je dan komen tot een stuk met richtlijnen die je kan gebruiken bij het opstellen van domeinarchitecturen.

Eerste constatering is dat vooral naar CG is gekeken en niet naar Gegevenslandschap.

**Comment by TCIMEddy** [comment]
Klinkt als een mooi eerste product!!! @jgortmaker1 Zet jij vinkje en sleep naar ready for sprint

**Comment by TCIMEddy** [comment]
Volgens mij hebben we besloten dat deze user story op dit moment done is omdat aan de vraag voldaan is. Wel dient het product continu aangepast te worden aan nieuwe inzichten. Tevens komen er user stories uit. Belangrijkste die ik heb opgevangen is duidelijkheid over informatiemodel @tschijv Wil jij deze indien nodig opvoeren. Ik kan deze niet reproduceren
