### ISSUE TITLE
Als Kernteam Common Ground wil ik een verdieping op het vijflagenmodel (in verbinding met de platen van het gegevenslandschap) kunnen aanbieden. (5)

### ISSUE THREAD

**Issue by jgortmaker1** [VNG-Realisatie/cg-architectuur#8]
...zodat ik een antwoord kan geven op complexere vragen rondom migratie en implementatie.

**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg 
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en leesbaar)
- [x] Voorzien van Definition of Done 
- [x] Voorzien van taken (naam, uren, smart)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Users en stakeholder benoemd
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [x] Document gereed en afgestemd op doelgroep
- [x] Potentieel publiceerbaar/beschikbaar voor users en stakeholders
- [x] Peer review heeft plaatsgevonden
- [x] Demo-gereed (kan getoond worden tijdens demo en is demo materiaal is gereed)
- [x] Product Owner akkoord

**Users**

- [ ] Architecten
- [ ] Product/business managers

**Stakeholders**

- [ ] Leveranciers
- [ ] Gemeenten
- [ ] VNG Realisatie

**Acceptatiecriteria**

- [x] duidelijk en leesbaar voor doelgroep (users/stakeholders)
- [x] de relatie tussen de verschillende gemeentelijke bewegingen (common ground, +1 gemeente en samen organiseren) is beschreven
- [x] aanleiding common ground/gegevenslandschap is beschreven
- [x] visie ten aanzien van toekomstige architectuur is beschreven conform indeling common ground
- [x]  de lagen van het common ground model zijn op hoofdlijnen functioneel beschreven
- [x] het opgeleverde product is demonstrabel (Powerpoint presentatie)

**Taken**

- [x] inventariseren doelen gemeentelijke bewegingen en in onderling verband beschrijven
- [x] uitwerken toekomstscenario
- [x] uitwerken van het common ground model in functionaliteiten op hoofdlijnen
- [x] peer review (team)
- [x] demoversie maken

**Comment by WimBakkeren** [comment]
Waar bestaat deze verdieping uit?
En wat zijn dan de vragen waar je antwoord op wil kunnen geven?
Er is een userstory die vraagt hoe we Common Ground denken te implementeren in een situatie waarin gemeenten (standaard) software van leveranciers inkopen. Gaat deze userstory daar ook antwoord op geven?
Volgens mij is deze userstory te 'slicen' door een beperkt aantal vragen te formuleren waarop de verdieping een antwoord moet geven ipv op 'alle' complexere vragen rondom migratie en implementatie.

**Comment by jgortmaker1** [comment]
@arnoudquanjer deze is nog niet ready. volgens mij was het hier de bedoeling om een bijgewerkte versie van "het gegevenslandschap" op te leveren en daarin de 5-lagen van CG terug te laten komen..

deze US is nu denk ik wat te breed

**Comment by TCIMEddy** [comment]
@arnoudquanjer kun je uit de voeten met deze user story of is het nog te breed (zie opmerking jeffrey). Mocht je al bezig zijn, wil je hem dan in progress zetten.

**Comment by TCIMEddy** [comment]
Demo feedback:
- DSO apart of binnen Samen Organiseren
- naamgeving
- voldoende feedback
- serviceregister?
- landelijke authenticatie in dit verhaal?
- functionaliteit nodig om services te kunnen vinden
- waar is dit de architectuur van? waar doe je uitspraken over?
- wat is de status van het document

**Comment by TCIMEddy** [comment]
ik ben zo vrij geweest om alles af te vinken omdat deze user story done is. Feedback heb ik in bovenstaand commentaar verwerkt.
