### ISSUE TITLE
Als scrumteam wil ik een set met architectuurprincipes voor het gegevenslandschap hebben (zie: sharepoint))

### ISSUE THREAD

**Issue by jgortmaker1** [VNG-Realisatie/cg-architectuur#95]
...zodat we een kader hebben voor het uitwerken van user stories

**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg 
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en leesbaar)
- [x] Voorzien van Definition of Done 
- [x] Voorzien van taken (naam, uren, smart)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Users en stakeholder benoemd
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [ ] Document gereed en afgestemd op doelgroep
- [ ] Potentieel publiceerbaar/beschikbaar voor users en stakeholders
- [x] Peer review heeft plaatsgevonden
- [x] Demo-gereed (kan getoond worden tijdens demo en is demo materiaal is gereed)
- [ ] Product Owner akkoord

**Users**

- [ ] scrumteam
- [ ] product owner

**Stakeholders**
- [ ] opdrachtgever
- [ ] kernteam common ground
- [ ] product owner

**Acceptatiecriteria**

- [ ] Duidelijk en leesbaar voor doelgroep (users/stakeholders)
- [ ] Voldoet aan principes Common Ground (droste effect?)
- [ ] Sluit aan op de 'visie'-samenhang,  zie #9 

**Globale oplossingsrichting**
- Uitwerken obv bestaande stukken gegevenslandschap/CG/1+gemeente/GEMMA2/NORA
- Uitwerken in Archimate-motivation extention voor de structuur en decompositie
- Hoofdprincipes en requirements.

**Taken**
- [ ] Opstellen eerste versie (Ad, Toine)
- [ ] Peer review (team)
- [ ] Demoversie maken (scherpe lijst principes)

**Comment by jgortmaker1** [comment]
@adgerrits @tschijv is voor mij ready voor sprint 1

**Comment by adgerrits** [comment]
@arnoudquanjer en @jgortmaker1 gevraagd voor eerste review.

**Comment by tschijv** [comment]
Hoi Ad,

Wat mij en Jeffrey betreft, kunnen we het naar de hele squad sturen. Er komen nog heel wat reviews aan. Dan hoeft de squad niet alles tegelijkertijd te lezen. Wat vind jij?





Met vriendelijke groeten,
Toine Schijvenaars

VNG Realisatie
Nassaulaan 12
2514 JS Den Haag
www.vngrealisatie.nl<http://www.vngrealisatie.nl>
www.gemmaonline.nl<http://www.gemmaonline.nl>

toine.schijvenaars@vng.nl<mailto:voornaam.achternaam@vng.nl>
06 - 24 32 49 60




Op 4 okt. 2018, om 17:29 heeft Ad Gerrits <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@arnoudquanjer<https://github.com/arnoudquanjer> en @jgortmaker1<https://github.com/jgortmaker1> gevraagd voor eerste review.

**Comment by adgerrits** [comment]
Prima. Voor wie wil reageren: het gemaakt document staat op [Google Docs](https://docs.google.com/document/d/19cVyYeCIKEs00eO-7NEKURBwnKZgidjesKqB59_d318/edit?usp=sharing). Inloggen niet verplicht maar wel handig om te weten wie wat zegt. Ik zal de link ook achter de omschrijving plakken zodat beter zichtbaar wordt waar het document staat.

**Comment by markbacker** [comment]
@adgerrits;  @tschijv  ik heb m'n review naast het document op sharepoint gezet. Letters MB achter de naam geplakt.

**Comment by adgerrits** [comment]
Met dank Mark. Je opmerkingen van commentaar voorzien in jouw document op sharepoint. Ga wijzigingen nu verwerken in het brondocument. Paar belangrijke punten:
- samenhang GGL, CG ed laat ik bij Jeffrey ('eenmalige vastlegging')
- principes zijn voor Gegevenslandschap, niet Common Ground
- vijflagenmodel is een hulpmiddel ter verduidelijking, niet om principes aan op te hangen
- goeie suggesties voor 2 mogelijjke principes (complexiteitreductie, services)
- 'componenten' is bewust gekozen tov 'functies' en 'lagen' (to be discussed)

**Comment by jgortmaker1** [comment]
review gedaan..zie sharepoint..document met opm MB..

**Comment by TCIMEddy** [comment]
Demo feedback:
- semantiek
- complimenten helder
- kwaliteit gegevens
- stip op de horizon

**Comment by jgortmaker1** [comment]
kan deze niet op close.
volgens mij was het aanscherpen van dit setje principes bedoeld in #120
